---

  - name: create mysql database
    mysql_db: name=training_db state=present

  - name: create mysql user
    mysql_user: name=brightech host={{ item }} password=brightech priv=training_db.*:ALL,GRANT state=present
    with_items:
      - localhost